/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quizapplication;

//importing packages/statements....
import java.awt.Font;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

public class log extends javax.swing.JFrame {

    static String uname;

    private static String password, selectedRole;
    private static final String FILEPATH = "C:\\Users\\User\\Documents\\NetBeansProjects\\quizApplication\\src\\quizapplication\\users.json";
    private final JSONParser opener = new JSONParser();
    private JSONArray teacherList = new JSONArray();
    private JSONArray studentList = new JSONArray();
    Thread t;

    public log() {
        initComponents();
        loadUserData();
        loadRememberedUser();
        try {
            File fontStyle = new File("C:\\Users\\User\\Documents\\NetBeansProjects\\quizApplication\\test\\fonts\\Heiback - PERSONAL USE ONLY.ttf");
            Font fo = Font.createFont(Font.TRUETYPE_FONT, fontStyle).deriveFont(44f);
            text.setFont(fo);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadUserData() {
        try (FileReader reader = new FileReader(FILEPATH)) {
            JSONObject data = (JSONObject) opener.parse(reader);
            teacherList = (JSONArray) data.get("teacher");
            studentList = (JSONArray) data.get("student");
        } catch (IOException | ParseException ex) {
            JOptionPane.showMessageDialog(this, "Error loading user data: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        keeptoo.KGradientPanel kGradientPanel1 = new keeptoo.KGradientPanel();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        text = new javax.swing.JLabel();
        role = new javax.swing.JComboBox<>();
        keeptoo.KGradientPanel kGradientPanel2 = new keeptoo.KGradientPanel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        jname = new javax.swing.JTextField();
        jpas = new javax.swing.JPasswordField();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        remember = new javax.swing.JCheckBox();
        create = new javax.swing.JButton();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        log1 = new javax.swing.JButton();
        show = new javax.swing.JCheckBox();
        javax.swing.JLabel wel1 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setBackground(new java.awt.Color(0, 153, 153));
        kGradientPanel1.setkEndColor(new java.awt.Color(206, 92, 165));
        kGradientPanel1.setkStartColor(new java.awt.Color(240, 122, 46));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizapplication/output-onlinegiftools (1).gif"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4))
        );

        text.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        text.setForeground(new java.awt.Color(247, 247, 247));
        text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text.setText("Brain Box");

        role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Teacher", "Student" }));
        role.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roleMouseClicked(evt);
            }
        });
        role.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleActionPerformed(evt);
            }
        });

        kGradientPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 14), new java.awt.Color(247, 247, 247))); // NOI18N
        kGradientPanel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        kGradientPanel2.setkEndColor(new java.awt.Color(206, 92, 165));
        kGradientPanel2.setkGradientFocus(430);
        kGradientPanel2.setkStartColor(new java.awt.Color(221, 106, 109));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(247, 247, 247));
        jLabel2.setText("User Name:");

        jname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jname.setForeground(new java.awt.Color(0, 51, 51));
        jname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jnameMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jnameMouseReleased(evt);
            }
        });
        jname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnameActionPerformed(evt);
            }
        });

        jpas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jpas.setForeground(new java.awt.Color(0, 51, 51));
        jpas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpasMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jpasMouseReleased(evt);
            }
        });
        jpas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpasActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(247, 247, 247));
        jLabel3.setText("Don't have an account yet?");

        remember.setBackground(new java.awt.Color(215, 101, 128));
        remember.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        remember.setForeground(new java.awt.Color(247, 247, 247));
        remember.setText("Remember me");
        remember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rememberActionPerformed(evt);
            }
        });

        create.setBackground(new java.awt.Color(211, 97, 143));
        create.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        create.setForeground(new java.awt.Color(0, 51, 204));
        create.setText("Sign Up");
        create.setBorder(null);
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(247, 247, 247));
        jLabel5.setText("Password:");

        log1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        log1.setForeground(new java.awt.Color(0, 51, 51));
        log1.setText("Login");
        log1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                log1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                log1MouseEntered(evt);
            }
        });
        log1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log1ActionPerformed(evt);
            }
        });

        show.setBackground(new java.awt.Color(212, 98, 140));
        show.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        show.setForeground(new java.awt.Color(247, 247, 247));
        show.setText("Show Password");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jname)
                            .addComponent(jpas)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(create, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                        .addComponent(remember)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(show)))
                .addGap(122, 122, 122))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                        .addComponent(log1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)))
                .addGap(173, 173, 173))
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jname))
                .addGap(25, 25, 25)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jpas)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(remember, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(show))
                .addGap(18, 18, 18)
                .addComponent(log1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(create)
                    .addComponent(jLabel3))
                .addGap(148, 148, 148))
        );

        wel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        wel1.setForeground(new java.awt.Color(247, 247, 247));
        wel1.setText("Welcome Back!");

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(kGradientPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 416, Short.MAX_VALUE)
                        .addGap(47, 47, 47))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(wel1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                        .addComponent(role, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(text, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(151, 151, 151))))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wel1)
                    .addComponent(role, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(text, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpasActionPerformed

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        SignUp up = new SignUp();
        up.pack();
        up.setVisible(true);
        up.setLocationRelativeTo(null);
        this.dispose();

    }//GEN-LAST:event_createActionPerformed

    private void jnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jnameActionPerformed

    private void rememberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rememberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rememberActionPerformed

    private void log1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log1ActionPerformed
        uname = jname.getText().trim();
        password = new String(jpas.getPassword()).trim();
        selectedRole = ((String) role.getSelectedItem()).toLowerCase();

        if (uname.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Username and password cannot be empty.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        JSONArray userList = selectedRole.equals("teacher") ? teacherList : studentList;
        boolean isAuthenticated = authenticateUser(userList);

        // Additional check for Teacher role misselection
        if (!isAuthenticated) {
            JSONArray alternateList = selectedRole.equals("teacher") ? studentList : teacherList;
            boolean isInAlternateRole = authenticateUser(alternateList);
            if (isInAlternateRole) {
                JOptionPane.showMessageDialog(this, "You are registered as a "
                        + (selectedRole.equals("teacher") ? "Student" : "Teacher")
                        + ". Please select the correct role.", "Login Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Additional check for Teacher role misselection
            if (!isAuthenticated && authenticateUser(teacherList)) {
                JOptionPane.showMessageDialog(this, "You are registered as a Teacher. Please select the correct role.",
                        "Login Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            JOptionPane.showMessageDialog(this, "Invalid Username or Password. Please try again.",
                    "Login Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (isAuthenticated) {
            // Non-blocking success message
            
            JDialog dialog = new JDialog(this, "Success", true);
            JLabel messageLabel = new JLabel("Login Successfully", JLabel.CENTER);
            messageLabel.setFont(new Font("Arial", Font.PLAIN, 14));
            dialog.add(messageLabel);
            dialog.setSize(300, 150);
            dialog.setLocationRelativeTo(this);

// Set timer to automatically close the dialog and redirect
            Timer timer = new Timer(1000, e -> {
                dialog.dispose(); // Close the message dialog after 1 second
                // Redirect to the appropriate panel
                if ("teacher".equals(selectedRole)) {
                    adminPanels ad = new adminPanels(uname);
                    ad.setVisible(true);
                    ad.pack();
                    ad.setLocationRelativeTo(null);
                } else if ("student".equals(selectedRole)) {
                    studentPanels st = new studentPanels(uname);
                    st.setVisible(true);
                    st.pack();
                    st.setLocationRelativeTo(null);
                    this.dispose();
                }
                 // Close the login form
            });
            timer.setRepeats(false); // Ensure the timer only runs once
            timer.start();

            dialog.setVisible(true); // Display the dialog
        }
    }//GEN-LAST:event_log1ActionPerformed

    private void roleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleActionPerformed

    private void jnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jnameMouseClicked
        jname.setText("");
    }//GEN-LAST:event_jnameMouseClicked

    private void jpasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpasMouseClicked
        jpas.setText("");
    }//GEN-LAST:event_jpasMouseClicked

    private void jnameMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jnameMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jnameMouseReleased

    private void jpasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpasMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jpasMouseReleased

    private void roleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roleMouseClicked

    }//GEN-LAST:event_roleMouseClicked

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        if (show.isSelected()) {
            jpas.setEchoChar((char) 0);
        } else {
            jpas.setEchoChar('*');
        }

    }//GEN-LAST:event_showActionPerformed

    private void log1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_log1MouseClicked
        jname.setText("");
        jpas.setText("");
    }//GEN-LAST:event_log1MouseClicked

    private void log1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_log1MouseEntered

    }//GEN-LAST:event_log1MouseEntered

    private boolean authenticateUser(JSONArray userList) {
        for (Object obj : userList) {
            JSONObject user = (JSONObject) obj;
            String userName = (String) user.get("username");
            String userPass = (String) user.get("password");

            if (uname.equals(userName) && password.equals(userPass)) {
                return true;
            }
        }
        return false;
    }

    private void rememberUser(String user, String pass, String role) {
        try (FileWriter file = new FileWriter("remember.json")) {
            JSONObject obj = new JSONObject();
            obj.put("username", user);
            obj.put("password", pass);
            obj.put("role", role);
            file.write(obj.toJSONString());
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private void loadRememberedUser() {
        File file = new File("remember.json");
        if (!file.exists()) {
            return;
        }

        try (FileReader reader = new FileReader(file)) {
            JSONObject obj = (JSONObject) opener.parse(reader);
            jname.setText((String) obj.get("username"));
            jpas.setText((String) obj.get("password"));
            role.setSelectedItem((String) obj.get("role"));
            remember.setSelected(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void forgetUser() {
        File file = new File("remember.json");
        if (file.exists()) {
            file.delete();
        }
    }

    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(() -> {
            log log1 = new log();
            log1.setVisible(true);
            log1.pack();
            log1.setLocationRelativeTo(null);

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton create;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jname;
    private javax.swing.JPasswordField jpas;
    private javax.swing.JButton log1;
    private javax.swing.JCheckBox remember;
    private javax.swing.JComboBox<String> role;
    private javax.swing.JCheckBox show;
    private javax.swing.JLabel text;
    // End of variables declaration//GEN-END:variables
}
